version: '3.1'

services:

  api-service:
    build:
      context: .
      dockerfile: ./api-service.dockerfile
    restart: always
    ports:
      - "8800:8800"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./data:/data
    environment:
      - DSN=rest_api_user:rest_api_pw@tcp(db-service:3306)/rest_server?charset=utf8&parseTime=True&loc=Local


  db-service:
    image: mariadb
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rest_server
      MYSQL_USER: rest_api_user
      MYSQL_PASSWORD: rest_api_pw
    volumes:
      - ./data:/var/lib/mysql
    # ports:
    #   - "3306:3306"

